<?php
namespace Litovchenko\AirTable\Hooks\Frontend;

use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController;
use Litovchenko\AirTable\Utility\BaseUtility;

class CreateHashBase
{
	/**
     * The magic variable TYPO3 
     * Parameters are described here 
     * @var array
     */
	public static $TYPO3 = [
		'thisIs' => 'Hooks',
		'name' => 'Добавляем переменных значений в "HashBase" страницы',
		'description' => '',
		'onlyFrontend' => [
			'TYPO3_CONF_VARS|SC_OPTIONS|tslib/class.tslib_fe.php|createHashBase::createHashBase'
		]
	];
	
    /**
     * Modify the cache hash
     *
     * @param array &$params Array of parameters: hashParameters,
     *                       createLockHashBase
     * @param null  $ref     Reference object
     * @return void
     */
    public function createHashBase(&$params, $ref)
    {
		// eIdAjax
		$eIdAjax = \TYPO3\CMS\Core\Utility\GeneralUtility::_GET('eIdAjax');
		if(!empty($eIdAjax)){
			$params['hashParameters']['eIdAjax'] = true;
		} else {
			$params['hashParameters']['eIdAjax'] = false;
		}
		
		// Method
		$params['hashParameters']['requestMethod'] = $GLOBALS['_SERVER']['REQUEST_METHOD'] === 'POST' ? 'POST' : 'GET';
		
		// Editing
		if($GLOBALS['BE_USER']){
			$params['hashParameters']['beUserLogin'] = 1;
			$params['hashParameters']['beUserSesId'] = $GLOBALS['BE_USER']->user['ses_id'];
			$params['hashParameters']['phptemplate_mode_editing'] = $GLOBALS['BE_USER']->uc['phptemplate_mode_editing'];
			$params['hashParameters']['phptemplate_showHiddenRecords'] = $GLOBALS['BE_USER']->uc['phptemplate_showHiddenRecords'];
			$params['hashParameters']['phptemplate_noResizeImage'] = $GLOBALS['BE_USER']->uc['phptemplate_noResizeImage'];
			$params['hashParameters']['phptemplate_checkOption'] = $GLOBALS['BE_USER']->uc['phptemplate_checkOption'];
			$params['hashParameters']['isMoveRecord_tt_content'] = $GLOBALS['BE_USER']->uc['isMoveRecord_tt_content'];
		} else {
			$params['hashParameters']['beUserLogin'] = 0;
		}
		
		/*
		Array
		(
			[hashParameters] => Array
				(
					[id] => 1
					[type] => 0
					[groupIds] => 0,-1
					[MP] => 
					[site] => autogenerated-1-c4ca4238a0
					[siteBase] => http://ivan-litovchenko.ru/
					[staticRouteArguments] => Array -> Вот этот параметр...
						(
							[tx_projiv_pagedefaultcontroller] => Array
								(
									[action] => travelView
									[controller] => Pages\PageDefault
								)

						)

					[dynamicArguments] => Array
						(
						)

					[eIdAjax] => 
					[beUserLogin] => 1
					[phptemplate_mode_editing] => 1
					[phptemplate_showHiddenRecords] => 
					[phptemplate_noResizeImage] => 
					[phptemplate_checkOption] => -1
					[isMoveRecord_tt_content] => 0
					[requestMethod] => GET
				)

			[createLockHashBase] => 1
		)
		*/
		
		// Tags
		// $_GET = \TYPO3\CMS\Core\Utility\GeneralUtility::_GET();
		if(BaseUtility::isPageVp() == true)
		{
			// Ищем в таблице кэш с такими тэгами...
			$cacheTag = 'pageVp_'.md5(serialize($GLOBALS['TSFE']->pageArguments->getRouteArguments())); // getPageId
			$filter = [];
			$filter['select'] = ['id','identifier','tag'];
			$filter['from'] = [T3_CACHE_TABLE_TAGS];
			$filter['where'] = ['tag','=',$cacheTag];
			$count = \Litovchenko\AirTable\Domain\Model\DynamicModelCrud::recSelect('count',$filter);
			// $rows = DB::table(T3_CACHE_TABLE_TAGS); // use Illuminate\Database\Capsule\Manager as DB;
			
			// Если не находит, отправляем не кэшировать страницу
			$func = 'cache';
			if($count == 0){
				$GLOBALS['TSFE']->set_no_cache(); // $GLOBALS['TSFE']->set_cache_timeout_default(0);
				$func = 'set_no_cache';
			}
			$params['hashParameters']['pageVp'] = $cacheTag;
			// $GLOBALS['TTTT'] = "<div style='position: fixed; top: 10%; left: 50%; z-index: 10000; background: red;'>".$func." > ".$cacheTag."</div>";
			// $GLOBALS['TTTT'] .= "<div style='position: fixed; top: 15%; left: 50%; z-index: 10000; background: red;'><pre>".print_r($cacheTag,true)."</pre></div>";
		}
    }
}